CREATE TABLE Users(
	Email VARCHAR(30) NOT NULL PRIMARY KEY,
	Password NVARCHAR(50) NOT NULL,
	Role INT NOT NULL,
	Enabled BIT NOT NULL,
	Fullname NVARCHAR(50) NOT NULL,
	Mobile NVARCHAR(20) NOT NULL,
)

CREATE TABLE Products(
	Id VARCHAR(20) NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Image NVARCHAR(50) NOT NULL,
	Price FLOAT NOT NULL,
	Quantity INT NOT NULL,
	Available BIT NOT NULL,
	Prodate DATE NOT NULL,
	Description NVARCHAR(255) NOT NULL,
)

CREATE TABLE Orders(
	Id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	Email VARCHAR(30) NOT NULL REFERENCES Users(Email),
	OrderDate DATE NOT NULL,
	OrderStatus INT NOT NULL
)

CREATE TABLE OrderLines(
	Id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	OrderId BIGINT NOT NULL REFERENCES Orders(Id) ON DELETE CASCADE,
	ProductId VARCHAR(20) NOT NULL REFERENCES Products(Id),
	Quantity INT NOT NULL,
	Price FLOAT NOT NULL
)

CREATE TABLE CartItems(
	Id BIGINT IDENTITY NOT NULL PRIMARY KEY,
	Owner VARCHAR(30) NOT NULL,
	ProductId VARCHAR(20) NOT NULL REFERENCES Products(Id),
	Quantity INT NOT NULL
)